<div class="block-login">
                    <div class="block-login-logo">
<!--                        <a class="logo">Cody's</a>-->
                    </div>                    
                    <div class="block-login-content">
                        <h1>Sign in</h1>
                        <form id="signinForm" method="post" action="index.html">
                            
                        <div class="form-group">                        
                            <input type="text" name="login" class="form-control" placeholder="Your login/e-mail" value="Administrator"/>
                        </div>
                        <div class="form-group">                        
                            <input type="password" name="password" class="form-control" placeholder="Your password" value="Password"/>
                        </div>
                        <div class="pull-left">
                            <div class="checkbox">
                                <label><input type="checkbox" name="keep"/> Keep me signed in</label>
                            </div>
                        </div>                                        
                        <div class="pull-right">
                            <a href="#">Forgot password?</a>
                        </div>

                        <button class="btn btn-primary btn-block" type="submit">Sign in</button>                                        
                        
                        </form>
                        <div class="sp"></div>

                        <button class="btn btn-success btn-block" onClick="location.href='pages-signup.html'">Create an account</button>                    

<!--                        <p class="tac">Or use</p>

                        <div class="pull-left" style="width: 45%;">
                            <button class="btn btn-block btn-primary btn-facebook"><i class="fa fa-facebook pull-left"></i> Facebook</button>
                        </div>
                        <div class="pull-right" style="width: 45%;">
                            <button class="btn btn-block btn-info btn-tweeter"><i class="fa fa-twitter pull-left"></i> Twitter</button>
                        </div>-->

                        <div class="sp"></div>
                        <div class="pull-left">
							Cody's workbench <?php echo date('Y'); ?>
                        </div>
                    </div>
					
</div>